---
title: "Foils for Chapter 3 in linear algebra and numerical methods"
author: "Øyvind Ryan"
date: last-modified
format: 
    beamer:
        classoption: ["t", "notheorems"]
echo: true
---


```{python}
#| include: false
{{< include _imports.py >}}
```

## Gaussian elimination

---

## A general system with $m$ equations and $n$ unknowns:
$$
\begin{aligned}
\begin{array}{lllll}
a_{11}x_1 &+ a_{12}x_2 &+ \cdots &+ a_{1n}x_n &= b_1 \\
a_{21}x_1 &+ a_{22}x_2 &+ \cdots &+ a_{2n}x_n &= b_2 \\
\vdots        & \vdots         & \vdots    & \vdots         & \vdots\\
a_{m1}x_1 &+ a_{m2}x_2 &+ \cdots &+ a_{mn}x_n &= b_m
\end{array}
\end{aligned}
$$ {#eq-rowrednew0}
Chapter 2. we wrote this more compactly as $A\mathbf{x}=\mathbf{b}$,

---

## Procedure in Gaussian elimination
The system $A\mathbf{x}=\mathbf{b}$ is solved by systematically eliminating variables from left to right. 
Suppose that the variables $x_1,...,x_n$ have been eliminated. There are two  possibilities:

1. $x_{n+1}$ does not appear in the remaining equations. Then $x_{n+1}$ has been eliminated as well, and we proceed with the elimination of $x_{n+2}$.
2. $x_{n+1}$ appears in at least one of the remaining equations. We do the following:
    (a) Take one of the equations where $x_{n+1}$ appears, and place this first among the remaining equations. 
    (b) Scale this equation so that there is a $1$ in front of $x_{n+1}$. We shall call this a *leading one*\index{Leading one} (there should be no contribution left of $x_{n+1}$ in this equation).
    (c) Add multiples of this equation to the other remaining equations so that $x_{n+1}$ gets eliminated. 
    
We have now eliminated $x_{n+1}$, and proceed with the elimination of $x_{n+2}$.
    
---    

## A system with a unique solution

$$
\begin{array}{rrrr}
        & -8x_2&+3x_3=& 6 \\
 4x_1& -3x_2&+2x_3=& 8\\
  x_1& -2x_2& + x_3=& 3
\end{array}
$$

---

---

## The augmented matrix

We will assemble both $A$ and $\mathbf{b}$ in the bigger matrix $\begin{pmatrix}A & \mathbf{b}\end{pmatrix}$, 
called the *augmented matrix*\index{Augmented matrix} of the system. For the example above: 
$$
\begin{aligned}
A &= \begin{pmatrix} 0 & -8 & 3 \\ 4 & -3 & 2 \\ 1 & -2 & 1 \end{pmatrix} & 
\mathbf{b} &= \begin{pmatrix} 6 \\ 8 \\ 3 \end{pmatrix} &
\begin{pmatrix}A & \mathbf{b}\end{pmatrix} &= \begin{pmatrix} 0 & -8 & 3 & 6 \\ 4 & -3 & 2 & 8 \\ 1 & -2 & 1 & 3 \end{pmatrix}
\end{aligned}
$$

* An equation: a row in the augmented matrix.
* A variable: a column in the coefficient matrix $A$. 
* Pivot row: A row with a leading one.
* Pivot column: A column with a leading one.

---

## Gaussian elimination on matrix form

$$
\begin{aligned}
\begin{pmatrix} 0 & -8 & 3 & 6 \\ 4 & -3 & 2 & 8 \\ 1 & -2 & 1 & 3 \end{pmatrix}
&\sim
\begin{pmatrix} 1 & -2 & 1 & 3 \\ \textcolor{red}{4} & -3 & 2 & 8 \\ 0 & -8 & 3 & 6 \end{pmatrix}
\sim
\begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 5 & -2 & -4 \\ 0 & -8 & 3 & 6 \end{pmatrix} \\
&\sim
\begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} \\ 0 & \textcolor{red}{-8} & 3 & 6 \end{pmatrix}
\sim
\begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} \\ 0 & 0 & -\frac{1}{5} & -\frac{2}{5} \end{pmatrix} \\
&\sim
\begin{pmatrix} 1 & -2 & \textcolor{red}{1} & 3 \\ 0 & 1 & \textcolor{red}{-\frac{2}{5}} & -\frac{4}{5} \\ 0 & 0 & 1 & 2 \end{pmatrix}
\sim
\begin{pmatrix} 1 & \textcolor{red}{-2} & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 2 \end{pmatrix} \\
&\sim
\begin{pmatrix} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 2 \end{pmatrix}
\end{aligned}
$$ {#eq-rowrednew}
$\sim$ denotes one of the operations we performed.

---

## Gaussian elimination with `sympy`.
```{python}
C, cols = sym.Matrix([[0,-8,3,6],
                      [4,-3,2,8],
                      [1,-2,1,3]]).rref()
print(C)
```

The same matrix was obtained. This is not obvious (there are many different ways to bring a matrix to reduced echelon form). 

Next week: Yes, the reduced echelon form is actually unique!

---

## Gaussian elimination with the operations indicated

1. The first operation swapped row 1 and 3. Will write this as $I\leftrightarrow III$. 
2. The second operation subtracted 4 times row 1 in row 2. Will write this as $II-4I$. 
3. The third operation multiplied row $2$ with $1/5$. Will write this as $II\cdot(1/5)$.
 
 $$
\begin{aligned}
&\begin{pmatrix} 0 & -8 & 3 & 6 \\ 4 & -3 & 2 & 8 \\ 1 & -2 & 1 & 3 \end{pmatrix} \stackrel{I\leftrightarrow III}{\sim}\begin{pmatrix} 1 & -2 & 1 & 3 \\ 4 & -3 & 2 & 8 \\ 0 & -8 & 3 & 6 \end{pmatrix} \\
&\stackrel{II-4I}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 5 & -2 & -4 \\ 0 & -8 & 3 & 6 \end{pmatrix}\stackrel{II\cdot(1/5)}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} \\ 0 & -8 & 3 & 6 \end{pmatrix}\\
&\stackrel{III+8II}{\sim}\begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} \\ 0 & 0 & -\frac{1}{5} & -\frac{2}{5} \end{pmatrix}\stackrel{III\cdot(-5)}{\sim}\begin{pmatrix} 1 & -2 & 1 & 3 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} \\ 0 & 0 & 1 & 2 \end{pmatrix}
\end{aligned}
$$

---

$$
\begin{aligned}
&\stackrel{II+\frac{2}{5}III,I-III}{\sim}\begin{pmatrix} 1 & -2 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 2 \end{pmatrix} \stackrel{I+2II}{\sim}\begin{pmatrix} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 2 \end{pmatrix}
\end{aligned} 
$$ {#eq-rowrednew2}

---

## Elementary row operations
The system was thus brought to reduced echelon form with help of *elementary row operations*:

1. Add a multiple of one row to another,
2. multiply a row with a constant $\neq 0$,
3. Swap two rows.

We say that $A$ and $B$ are *row equivalent* (written $A\sim B$) if we can transform $A$ to $B$ through a series of elementary 
row operations. From the discussion above:
$$
\begin{pmatrix} 0 & -8 & 3 & 6 \\ 4 & -3 & 2 & 8 \\ 1 & -2 & 1 & 3 \end{pmatrix} \sim \begin{pmatrix} 1 & 0 & 0 & 1 \\ 0 & 1 & 0 & 0 \\ 0 & 0 & 1 & 2 \end{pmatrix}.
$$
Every matrix is row equivalent to a matrix on reduced echelon form.

---

## Expressing elementary row operations in terms of matrices


::: {#prp-smh:elemradop}
Suppose $B$ is obtained by applying an elementary row operation to the $m\times n$-matrix $A$. 
Then $B=EA$ where $E$ is the matrix obtained by applying the same row operation to the identity matrix $I_m$.
:::

A matrix is called *elementary* if it is obtained by applying an elementary row operation to the identity matrix. 

Proof: 

---

## Examples of elementary matrices

$$
\begin{aligned}
E_1 &=\begin{pmatrix} 1 & 2 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} & 
E_2 &=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 3 \end{pmatrix} &
E_3 &=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{pmatrix}
\end{aligned}
$$ {#eq-reverseradops}

* $E_1$ corresponds to the row operation where we add $2$ times row $2$ to row $1$, 
* $E_2$ to the row operation where we multiply row $3$ with $3$, 
* $E_3$ to the row operation where we swap rows $2$ and $3$. 

---

## Row operations can be reversed

The reverse row operations of @eq-reverseradops are

* adding $-2$ times row $2$ to row $1$, 
* multiplying row $3$ with $1/3$, 
* swapping rows $2$ and $3$. 

Corresponding elementary matrices 
\begin{align*}
F_1 &=\begin{pmatrix} 1 & -2 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{pmatrix} & 
F_2 &=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1/3 \end{pmatrix} &
F_3 &=\begin{pmatrix} 1 & 0 & 0 \\ 0 & 0 & 1 \\ 0 & 1 & 0 \end{pmatrix}
\end{align*}
$F_i$ reverses $E_i$ means that 
\begin{align*}  F_1E_1&=I_3 & F_2E_2&=I_3 & F_3E_3&=I_3. \end{align*}

---

## Verification

by using Python:
```{python}
#| echo: true
import numpy as np

E_1 = np.array([[1,2,0],[0,1,0],[0,0,1]])
F_1 = np.array([[1,-2,0],[0,1,0],[0,0,1]])
E_1 @ F_1
```
with multiplication by hand:

---

## Factoring a matrix with elementary matrices


::: {#prp-}
For every matrix $A$ we can write 
$$C=E_k\cdots E_2E_1A$$
where $C$ is a matrix on reduced echelon form, and where $E_1,E_2,...,E_k$ are elementary matrices.
:::



---

## Solutions to a system are unchanged by elementary row operations

::: {#prp-}
Assume a system is obtained from another by applying an elementary row operation. 
Then the two systems have the same solutions. 
:::

Proof:

---

## A system with infinitely many solutions

$$
\begin{array}{rrrr}
x_1 & + x_2 & + x_3=& 4 \\
2x_1 & &-x_3=& 2.
\end{array}
$$

---

We observe: 
 
---

## A system without solutions

$$
\begin{array}{rrr}
x_1 & +x_2=& 2 \\
3x_1 & +3x_2=& 5 
\end{array}
$$

\vfill

\vfill

We observe:

---



## The three possibilities in the examples above 

A system can have

1. a unique solution (the first example). Here we had only pivot variables, and no pivot element in the last column.
2. infinitely many solutions (the second example). Here we had a free variable, and no pivot element in the last column.
3. no solutions (the third example). Here we had a pivot element in the last column.

We obtained a reduced echelon form in all examples. 

---

## These observations hold more generally

::: {#prp-gaussel}
Any system can be brought to reduced echelon form, and we have the following possibilities:

1. The system has no solutions. In this case the last column is a pivot column,
2. The system has solutions. In this case the last column is not a pivot column and we have that
    (a) when there are free variables the system has infinitely many solutions (any value of the free variables give a solution),
    (b) when there are no free variables (all columns except the last is a pivot column) the system has a unique solution.

:::





## Invertible matrix theorem, first version

{{< include gaussianelimination/invmatteo.qmd >}}

This result will be extended later.

Proof: 

---

---

## Gaussian elimination and complexity (not in the curriculum)

Suppose we have a system with $n$ equations and $n$ unknowns. How many operations (additions, multiplications, etc.) are needed to solve the system/bring it to reduced echelon form? 

Suppose for simplicity that the coefficient matrix $A$ is row equivalent with the identity matrix. 

::: {#prp- name='Number of operations in Gaussian elimination'}
\index{Operation count!Gaussian elimination}
Suppose that $A\sim I_n$. About $2n^3/3$ operations are required to bring $A$ to reduced echelon form. 
:::

---

## Simultaneous solution of systems

Suppose we want to solve two systems $A\mathbf{x}=\mathbf{b}_1$ and $A\mathbf{x}=\mathbf{b}_2$ (same coefficient matrix, different right hand sides). 

* Bring $A$ to reduced echelon form, $C$, 
* apply the same row operations to $\mathbf{b}_1$ and $\mathbf{b}_2$, and get $\mathbf{b}'_1$ and $\mathbf{b}'_2$: 

$$\begin{pmatrix} A & \mathbf{b}_1 & \mathbf{b}_2 \end{pmatrix} \sim \begin{pmatrix} C & \mathbf{b}'_1 & \mathbf{b}'_2 \end{pmatrix}$$
(row reducing $A$, $\mathbf{b}_1$, and $\mathbf{b}_2$ separately can also be done by row reducing $\begin{pmatrix} A & \mathbf{b}_1 & \mathbf{b}_2 \end{pmatrix}$ as a whole).
 
From $\begin{pmatrix} C & \mathbf{b}'_1 & \mathbf{b}'_2 \end{pmatrix}$ we find the solutions to the two systems.



---

## First example revisited

Our first example solved the system $A\mathbf{x}=\mathbf{b}_1$ where $\mathbf{b}_1=(6,8,3)$. Using the same row operations we can simultaneously solve 
the system $A\mathbf{x}=\mathbf{b}_2$ where $\mathbf{b}_2=(1,8,2)$:

$$
\begin{aligned}
\begin{pmatrix}A & \mathbf{b}_1 & \mathbf{b}_2 \end{pmatrix} &= \begin{pmatrix} 0 & -8 & 3 & 6 & 1\\ 4 & -3 & 2 & 8 & 8 \\ 1 & -2 & 1 & 3 & 2\end{pmatrix} \\
&\stackrel{I\leftrightarrow III}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 & 2 \\ 4 & -3 & 2 & 8 & 8 \\ 0 & -8 & 3 & 6 & 1\end{pmatrix} \\
&\stackrel{II-4I}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 & 2 \\ 0 & 5 & -2 & -4 & 0 \\ 0 & -8 & 3 & 6 & 1\end{pmatrix} \\
&\stackrel{II\cdot(1/5)}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 & 2\\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} & 0 \\ 0 & -8 & 3 & 6 & 1\end{pmatrix}
\end{aligned}
$$

---

$$
\begin{aligned}
&\stackrel{III+8II}{\sim}\begin{pmatrix} 1 & -2 & 1 & 3 & 2\\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} & 0 \\ 0 & 0 & -\frac{1}{5} & -\frac{2}{5} & 1 \end{pmatrix}\\
&\stackrel{III\cdot(-5)}{\sim} \begin{pmatrix} 1 & -2 & 1 & 3 & 2 \\ 0 & 1 & -\frac{2}{5} & -\frac{4}{5} & 0 \\ 0 & 0 & 1 & 2 & -5\end{pmatrix}\\
&\stackrel{II+\frac{2}{5}III,I-III}{\sim} \begin{pmatrix} 1 & -2 & 0 & 1 & 7 \\ 0 & 1 & 0 & 0 & -2 \\ 0 & 0 & 1 & 2 & -5\end{pmatrix} \\
&\stackrel{I+2II}{\sim}\begin{pmatrix} 1 & 0 & 0 & 1 & 3 \\ 0 & 1 & 0 & 0 & -2 \\ 0 & 0 & 1 & 2 & -5 \end{pmatrix}
\end{aligned}
$$
Thus, 

* $A\mathbf{x}_1=\mathbf{b}_1$ as before has the solution $\mathbf{x}_1=(1,0,2)$, 
* $A\mathbf{x}_2=\mathbf{b}_2$ has the solution $\mathbf{x}_2=(3,-2,-5)$.

---

## Skeleton for Gaussian elimination (not in the curriculum)
```{python}
#| eval: false
piv = np.zeros(m).astype(int) # Stores pivot positions
i, j = 0, 0
while i < m and j < n: # Start scan for next pivot
    k = i
    while k < m and abs(A[k,j]) < 10**(-6):
        k += 1
    if k == m: # Need to go to the next column
        j += 1
    else: # Found a nonzero in the current column
        # The next pivot element is in row k. If k>i, 
        # swap row i and k.
        # Create a leading one at pos. (i,j)
        # Zero out col. j below row i.
        piv[i] = j
        i += 1; j += 1
```