---
title: "Foils for Chapter 4 in linear algebra and numerical methods"
author: "Øyvind Ryan"
date: last-modified
format: 
    beamer:
        classoption: ["t", "notheorems"]
echo: true
---

```{python}
#| include: false
{{< include _imports.py >}}
{{< include gaussian_elimination.py >}}
```


# The inverse matrix

* Consider the system $A\mathbf{x}=\mathbf{b}$, with $A$ square. 
* If $A$ satisfies 1.-4. in the (first version of the) invertible matrix theorem, consider the mapping $T:\mathbf{b}\to\mathbf{x}$, 
which sends a given right hand side to the unique $\mathbf{x}$ solving $A\mathbf{x}=\mathbf{b}$. 
* $T$ is easily seen to be a linear transformation: 

---

* The matrix of this linear transformation will be denoted by $A^{-1}$, and called the *inverse* of $A$. 
* If we have found $A^{-1}$, we can solve any system $A\mathbf{x}=\mathbf{b}$ simply by computing $\mathbf{x}=A^{-1}\mathbf{b}$.

::: {#prp-}
Assume that $A$ satisfies 1.-4.. The following hold.

1. $A^{-1}A=AA^{-1}=I_n$. 
2. $A^{-1}$ also satisfies 1.-4..
3. $A$ is the inverse of $A^{-1}$.

:::

* We say that $A^{-1}$ is a left inverse of $A$ when $A^{-1}A=In$, 
* and a right inverse of $A$ when $AA^{-1}=I_n$.

Proof: 

---

---

* We say that $A$ is *invertible* when there exists a square matrix $B$ so that $BA=AB=I_n$. 
* When $A$ satisfies 1.-4., we saw that $A$ is invertible (set $B=A^{-1}$). 
* The other way, we will show that, if $A$ is invertible, it must satisfy 1.-4.. We will actually prove the following stronger statement: 

::: {#prp-}
If $AB=I_n$, then both $A$ and $B$ satisfy 1.-4. in the invertible matrix theorem (so that they are invertible). 
Also, $A$ and $B$ are inverses of one-another:
:::

It follows that a left inverse is automatically a right inverse as well, and that inverses are unique. 

Proof: 

---

---

We now extend the invertible matrix theorem with an equivalence concerning invertibility:

{{< include inverse/invmatteo.qmd >}}

---

## Invertibility and elementary matrices

* If $A$ is invertible we can write it as $A=E_k\cdots E_1$, where the $E_i$ are elementary matrices
* Write $B=F_1\cdots F_k$, where the $F_i$ are the reverse counterparts of the $E_i$. 

$F_i$ is the inverse of $E_i$ and $B$ is the inverse of $A$ since

$$BA = F_1\cdots F_kE_k\cdots E_1=I_n,$$
$$AB = E_k\cdots E_1F_1\cdots F_k=I_n,$$

---

## Some properties of the inverse matrix

* $\left(A^{-1}\right)^{-1}=A$
* if $s\neq 0$: $(sA)^{-1}=s^{-1}A^{-1}$

---

## Computing $A^{-1}$

Apply the row operations not only on $A$, but also on the augmented matrix $\begin{pmatrix} A & I_n \end{pmatrix}$. 

If $E_k\cdots E_1A=I_n$ we get $A^{-1}=E_k\cdots E_1$, and
$$E_k\cdots E_1\begin{pmatrix} A & I_n \end{pmatrix} = \begin{pmatrix} I_n & E_k\cdots E_1 \end{pmatrix} = \begin{pmatrix} I_n & A^{-1} \end{pmatrix}.$$
From the result we can read out $A^{-1}$ from the last columns. 

::: {#prp-}
Suppose that $A$ is invertible. The reduced echelon form of  $\begin{pmatrix} A & I_n \end{pmatrix}$ 
equals $\begin{pmatrix} I_n & A^{-1} \end{pmatrix}$. 
:::

Alternative interpretation: when row reducing $\begin{pmatrix} A & I_n \end{pmatrix}$, we simultaneously solve the systems
\begin{align*}
A\mathbf{x}_1&=\mathbf{e}_1 & A\mathbf{x}_2&=\mathbf{e}_2 & \cdots & \cdots & A\mathbf{x}_n&=\mathbf{e}_n,
\end{align*}
and since $A\mathbf{x}_i=\mathbf{e}_i$ implies that $A^{-1}\mathbf{e}_i=\mathbf{x}_i$, column $i$ in $A^{-1}$ will be $\mathbf{x}_i$:

---

## Example

Find the inverse of $A=\begin{pmatrix} 2 & 3 & 1 \\ 1 & 4 & 1 \\ 2 & 4 & 2 \end{pmatrix}$.

---

## Verification 1-2

With the built-in function for computing the inverse: 
```{python}
np.linalg.inv([[2,3,1],[1,4,1],[2,4,2]])
```
Symbolically:
```{python}
sym.Matrix([[2,3,1],[1,4,1],[2,4,2]]).inv()
```

---

## Verification 3

With the method `gaussian_elimination`, which we implemented:
```{python}
matr = np.block([[np.array([[2,3,1],[1,4,1],[2,4,2]], dtype='float64'), np.eye(3)]])
gaussian_elimination(matr, verbose=False)
matr[:,3:]
```

---

## Some of the elementary matrices

\begin{align*}
E_1 &= \begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1\end{pmatrix} &
E_2 &= \begin{pmatrix} 1 & 0 & 0 \\ -2 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} &
E_3 &= \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ -2 & 0 & 1 \end{pmatrix}
\end{align*}
and 
\begin{align*}
F_1 &= \begin{pmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1\end{pmatrix} &
F_2 &= \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ 0 & 0 & 1\end{pmatrix} &
F_3 &= \begin{pmatrix} 1 & 0 & 0 \\ 0 & 1 & 0 \\ 2 & 0 & 1 \end{pmatrix}
\end{align*}
With these we have that $A^{-1}=E_9\cdots E_1$, and $A=F_1\cdots F_9$.

---

## Example

Consider the system $A\mathbf{x}=\mathbf{b}$ with  $A=\begin{pmatrix} 2 & 3 & 1 \\ 1 & 4 & 1 \\ 2 & 4 & 2 \end{pmatrix}$ from the 
previous example, and where $\mathbf{b}=\begin{pmatrix} 19 \\ 21 \\ 26 \end{pmatrix}$. 
We found $A^{-1}$ above. 

Solution of the system is 
$$
\begin{aligned}
\mathbf{x}&=A^{-1}\mathbf{b} = \begin{pmatrix} 1 & -1/2 & -1/4 \\ 0 & 1/2 & -1/4 \\ -1 & -1/2 & 5/4 \end{pmatrix}\begin{pmatrix} 19 \\ 21 \\ 26 \end{pmatrix} \\
&= \\
&
\end{aligned}
$$

Gaussian elimination on the augmented matrix $\begin{pmatrix} A & \mathbf{b}\end{pmatrix}$ is to prefer, since
$\begin{pmatrix} A & I_n \end{pmatrix}$ has more columns than $\begin{pmatrix} A & \mathbf{b} \end{pmatrix}$.

---

## The Vandermonde matrix is invertible

We will prove by induction on $n$ that
$$
\begin{pmatrix}
1 & x_0 & x_0^2 & \cdots & x_0^n \\
1 & x_1 & x_1^2 & \cdots & x_1^n \\
1 & x_2 & x_2^2 & \cdots & x_2^n \\
\vdots & \vdots & \vdots & \ddots & \vdots \\
1 & x_n & x_n^2 & \cdots & x_n^n
\end{pmatrix}
$$ {#eq-solveforc}
is invertible if the generators $x_0,x_1,\dots,x_n$ are distinct:

---

---

## The Fourier matrix is invertible 

* Follows since it is a Vandermonde matrix in particular. 
* We have a general expression for its inverse, in contrast to the Vandermonde matrix:


Let $B$ the matrix with components $b_{kn}=\frac{1}{N}e^{2\pi ikn/N}$. We compute
$$(F_NB)_{kl}=$$
