# Preface {.unnumbered}

These notes were first written for the new first semester course MAT1105 - Linear algebra and numerical methods, 
at the University of Oslo. The course was held the first time the fall of 2024, 
and gives an introduction to basic mathematical thinking, linear algebra, and numerical methods. 
In the first version of the course, linear algebra was covered by chapter 1 and 4 in the book "Flervariabel analyse med lineær algebra" by Tom Lindstrøm (in norwegian), while the two other parts of the curriculum were covered by notes on their own.
In 2025 new notes for the linear algebra part were added, and merged with the notes on numerical analysis, even though the numerical analysis builds only loosely on linear algebra.

The notes contain many proofs, but many proofs in linear algebra are quite short, and are thus suitable following the mentioned introduction to basic mathematical thinking. 

The notes contain several Python programming examples, as well as an introduction to basic Python commands for linear algebra. 
Most students at the University of Oslo take the course 
[IN1900 - Introduction to Programming with Scientific Applications](https://www.uio.no/studier/emner/matnat/ifi/IN1900/), 
in parallel with the notes here. 
Linear algebra is a suitable testbed for Python programming, and the material contains many code snippets inspired by linear algebra. 
There are few figures in these notes - the role of figures is partially replaced by short programming examples with their graphical results shown.
It is recommended to spend some time on the programming examples. The following commands load the python packages you need.

```{python}
{{< include _imports.py >}}
```

The notes have been typeset with the Quarto publishing system (\href{https://quarto.org}{https://quarto.org}), 
and come in a pdf version, and an html version. 
Each of these come in a student version 
(i.e., without solutions to exercises, see [html book student version](https://erasmus-ctm.github.io/linalg-project/book-student)) 
and an instructor version 
(i.e., with solutions to exercises, see [html book instructor version](https://erasmus-ctm.github.io/linalg-project/book-instructor)). 

The notes are accompanied with a set of larger projects as well, also in both html and pdf, see
[html projects student version](https://erasmus-ctm.github.io/linalg-project/projects-student)
[html projects instructor version](https://erasmus-ctm.github.io/linalg-project/projects-instructor)
All of these (except pdf) are accessible from the [html main site](https://erasmus-ctm.github.io/linalg-project)

There is also a set of foils which were written in connection with lecturing the book, in the form of one beamer pdf per chapter. 
The foils contain a summary of main results, and annotation in the foils is used in the lectures. 

The html versions have some features not found in the pdf versions: 

* Each chapter has a quiz consisting of about 10 problems, and the quizzes aggregate the number of correct answers. 
* Interactive programming examples and exercises which use pyodide - i.e., python is embedded in the browser, without the need for a server.

In the html version all exercises where you compute something by hand can be verified with python programming. 
It is recommended that you actually spend some time on computing by hand before you run python code 
(or check the solutions) to verify the answer.


Parts of this material were originally based on material written by Knut Mørken for the course MAT-INF1100, Modelling and Computations, at the University of Oslo. 

Some comments on AI are in order.
Each python field has a feedback button, which sends the code in the field to AI, so that you get an explanation on 
what the code does. Each python field also supports code completion.

<!--
In the exercise section there is a link to more exercises. These are automatically generated by an AI which has been trained with the 
book.
-->

These notes are maintained in english. For those of you who prefer norwegian, AI will be used to create a translation. 

<!--
This material will be published non-commercially under Creative Commons licence Attribution-NonCommercial-ShareAlike (CC BY-NC-SA). 
I encourage people to adapt the material to their own need at their own university. 
I hope I can get something back - that some of these adaptions may be incorporated with the main material.  
My plan is to actively moderate the github repository.
-->


<!--
quarto render foils_chap1.qmd --output-dir build-beamer
quarto render foils_chap2.qmd --output-dir build-beamer
-->







\vspace{1.5cm}
\rightline{\em Blindern, August 2026}
\medskip
\rightline{\em Øyvind Ryan}

